<div class="list-wrapper">
    <div class="list-header"><?php echo $lang['about_us_label']; ?></div>
    <?php
        if (is_array($sk['terms']['about'])) {
            $i = 0;
            
            foreach ($sk['terms']['about'] as $text) {
                $i++;
                echo '<div class="list-column">
        <strong>' . $i . '</strong>. 
        ' . $text . '
    </div>';
            }
        }
    ?>
</div>