<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $sk['config']['site_title']; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="shortcut icon" href="<?php echo $sk['config']['site_url']; ?>/favicon.ico" />
    <link href="<?php echo $sk['config']['theme_url']; ?>/css/style.css" rel="stylesheet">
    <?php
    // CSS for welcome page
    if ($_GET['tab1'] == "welcome") {
        echo '<link href="' . $sk['config']['theme_url'] . '/css/welcome.css" rel="stylesheet">';
    }
    ?>
    <link href="<?php echo $sk['config']['theme_url']; ?>/css/font-awesome/font-awesome.css" rel="stylesheet">
    <!--[if IE 7]>
        <link href="<?php echo $sk['config']['theme_url']; ?>/css/font-awesome/font-awesome-ie7.css" rel="stylesheet">
    <![endif]-->
    <script src="<?php echo $sk['config']['theme_url']; ?>/javascript/jquery.1.10.2.min.js"></script>
    <?php
    // jQuery UI for Timeline page
    if ($_GET['tab1'] == "timeline") {
        echo '<script src="' . $sk['config']['theme_url'] . '/javascript/jquery-ui-1.10.4.custom.min.js"></script>';
        echo '<script src="' . $sk['config']['theme_url'] . '/javascript/jquery.ui.touch-punch.min.js"></script>';
    }
    ?>
    <script src="<?php echo $sk['config']['theme_url']; ?>/javascript/jquery-timeago.js"></script>
    <script src="<?php echo $sk['config']['theme_url']; ?>/javascript/jquery.form.min.js"></script>
    <?php
    if ($sk['config']['smooth_links'] == 1) {
        echo '<script>function SK_source(){return \'' . $sk['config']['ajax_path'] . '\';}</script>';
    } else {
        echo '<script>function SK_source(){return \'ajax.php\';}</script>';
    }
    
    if ($sk['logged'] == true) {
    ?>
    <script src="<?php echo $sk['config']['theme_url']; ?>/javascript/script.js"></script>
    <?php
    } else {
    ?>
    <script src="<?php echo $sk['config']['theme_url']; ?>/javascript/welcome.js"></script>
    <?php
    }
    
    // Open chat automatically from session
    if ($sk['config']['chat'] == 1) {
        
        if ($chat_recipient = SK_getChat()) {
            echo '<script>$(function() { SK_getChat(' . $chat_recipient['id'] . ',\'' . $chat_recipient['name'] . '\'); });</script>';
        }
    }
    ?>
</head>
<body>
    <?php echo SK_getPage('header/content'); ?>
    <div class="page-wrapper">
    <?php echo $sk['content']; ?>
    </div>
    
    <?php echo SK_getPage('footer/content'); ?>
    
    <?php
    if ($sk['logged'] == true && $sk['config']['chat'] == 1) {
        echo SK_getPage('chat/container');
    }
    ?>
    <audio id="notification-sound" preload="auto">
        <source src="<?php echo $sk['config']['theme_url']; ?>/sounds/notification.ogg" type="audio/ogg">
        <source src="<?php echo $sk['config']['theme_url']; ?>/sounds/notification.mp3" type="audio/mpeg">
        <source src="<?php echo $sk['config']['theme_url']; ?>/sounds/notification.wav" type="audio/wav">
    </audio>
</body>
</html>